services:
  python-app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "5000:5000"  # hôte:conteneur
    volumes:
      - .:/app  # Monte le dossier local dans le conteneur
    working_dir: /app
    restart: always
    command: python3 app.py  # Ou autre (ex: python3 app.py)
